### ISSUE TITLE
Snapshots not saving properly

### ISSUE THREAD

**Issue by vitota95** [conveyal/datatools-manager#30]
Hi everyone! 
First of all congratulations for this project, it looks pretty nice.

I'm trying to deploy the project with the dev branch. All is working ok but snapshots are not being saved how it should when uploading file because trips and patterns are not saving properly it remains to 0. The validation is working and it shows the number of trips etc.

I'm working without the S3 bucket, only local cache.

Can you figure out what is happening?

![snapshot_not_trips](https://cloud.githubusercontent.com/assets/24253459/22794848/c33c7e88-eef4-11e6-8737-9bad12fdaf0f.png)
![r5_pattern_created](https://cloud.githubusercontent.com/assets/24253459/22794847/c3399948-eef4-11e6-8650-8bc9f78cf7a1.png)

Thanks for your attention.

**Comment by landonreed** [comment]
Hi @vitota95, can you provide more info on the error/exception you're running into?

**Comment by vitota95** [comment]
Hi @landonreed!

There is no error or exception, but when I try to edit a feed it doesn't show any trip pattern because the snapshot is not saving the trips.

As you can see in this image the GTFS has trips and is validated.

![image](https://cloud.githubusercontent.com/assets/24253459/22893236/6b561818-f215-11e6-9063-c70ec31447dc.png)

But when I load for editing any trip pattern is appearing.

![image](https://cloud.githubusercontent.com/assets/24253459/22893508/29b69558-f216-11e6-97ac-175f39327682.png)

I have attached a [log.txt](https://github.com/conveyal/datatools-manager/files/771786/log.txt) file with all the log input that it shows when I upload the new feed version.

Thank you.

**Comment by landonreed** [comment]
Hi @vitota95, I'm not sure I can really devote much time to help with specific issues with feeds.  If you need more help, you're welcome to reach out to us for consulting services at contact@conveyal.com.
